spring:
  application:
    name: axon-microservice
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/axon_microservice}
    username: ${DB_USERNAME:axon}
    password: ${DB_PASSWORD:axon}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      query-projectors:
        mode: subscribing

logging:
  level:
    org.axonframework: INFO
    com.example.axonmicroservice: DEBUG


